oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_booking:
    resource: "@OCBookingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
