oc_booking_homepage:
    path:     /{page}
    defaults:
         _controller: OCBookingBundle:Booking:index
         page:
    requirements:
        page: \d*

oc_booking_view:
    path:      /booking/ticket/{id}
    defaults:
        _controller: OCBookingBundle:Ticket:view
    requirements:
        id: \d+
oc_mail:
    path:     /test
    defaults:
        _controller: OCBookingBundle:Booking:mail

oc_booking_customer:
    path:     /card
    defaults:
        _controller: OCBookingBundle:Booking:customer

oc_booking_contact:
    path:     /contact
    defaults:
        _controller: OCBookingBundle:Booking:contact

oc_booking_delete:
    path:     /delete/{sessionId}
    defaults:
        _controller: OCBookingBundle:Booking:delete


